app/user/forms.py
from app.models import User
from flask_babel import _
from flask_babel import lazy_gettext as _l
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, ValidationError


class EditProfileForm(FlaskForm):
    username = StringField(_l('Username'), validators=[DataRequired()])
    about_me = TextAreaField(_l('About me'), validators=[Length(min=0, max=140)])
    gender   = StringField('Gender', validators=[DataRequired()])
    submit   = SubmitField(_l('Submit'))

    def __init__(self, original_name, *args, **kwargs):
        # Username is saved as an instance variable,
        # and checked in validate_username() method.
        # If username entered in form is same as original username,
        # then there is no reason to check database for duplicates.
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_name = original_name
    
    def validate_username(self, username):
        if username.data != self.original_name:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError(_('Please use a different username.'))


class EmptyForm(FlaskForm):
    submit = SubmitField('Submit')

app/user/__init__.py
from flask import Blueprint

user_bp = Blueprint('user', __name__)

from app.user import routes

app/user/routes.py
from flask import (current_app, flash, redirect, render_template, request,
                   url_for)
from flask_babel import _
from flask_login import current_user, login_required

from app import db
from app.handler import UserHandler
from app.models import Post, User
from app.user import user_bp
from app.user.forms import EditProfileForm, EmptyForm


handler = UserHandler(current_app, current_user, db)

@user_bp.route('/user/<username>')
@login_required
def user(username):
    form  = EmptyForm()
    user  = User.query.filter_by(username=username).first_or_404()
    query = user.posts.order_by(Post.timestamp.desc())
    posts, prev_url, next_url = handler.pagination_user_posts(query, user, 'user.user')

    return render_template('user.html', user=user, posts=posts.items,
                           next_url=next_url, prev_url=prev_url, form=form)


@user_bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        handler.user_edit_profile(form)
        flash(_('Your changes have been saved.'))
        return redirect(url_for('user.edit_profile'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
        form.gender.data   = current_user.gender
    return render_template('edit_profile.html', title=_('Edit Profile'), form=form)


@user_bp.route('/follow/<username>', methods=['POST'])
@login_required
def follow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash(_(f'User {username} not found'))
            return redirect(url_for('main.index'))
        if user == current_user:
            flash(_('You cannot follow yourself!'))
            return redirect(url_for('user.user', username=username))
        current_user.follow(user)
        db.session.commit()
        flash(f'You are following {username}!')
        return redirect(url_for('user.user', username=username))
    else:
        return redirect(url_for('main.index'))


@user_bp.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash(_(f'User {username} not found'))
            return redirect(url_for('main.index'))
        if user == current_user:
            flash(_('You cannot unfollow yourself!'))
            return redirect(url_for('user.user', username=username))
        current_user.unfollow(user)
        db.session.commit()
        flash(f'You are following {username}!')
        return redirect(url_for('user.user', username=username))
    else:
        return redirect(url_for('main.index'))

app/templates/_post.html
    <table class="table table-hover">
        <tr>
            <td width="70px">
                <a href="{{ url_for('user.user', username=post.author.username) }}">
                    <img src="{{ post.author.avatar(70) }}" />
                </a>
            </td>
            <td>
                {% set user_link %}
                    <a href="{{ url_for('user.user', username=post.author.username) }}">
                        {{ post.author.username }}
                    </a>
                {% endset %}
                {{ _('%(username)s said %(when)s', username=user_link, when=moment(post.timestamp).fromNow()) }}
                <br>
                <p>{{ post.language }}:</p>

                <span id="post{{ post.id }}">{{post.body}}</span>
                {% if post.language and post.language != g.locale %}
                <div class="spinner-border" role="status"><span class="sr-only">Loading...</span></div>
                <br><br>
                <span id="translation{{ post.id }}">
                <a href="javascript:translate('#post{{ post.id }}',
                                              '#translation{{ post.id }}',
                                              '{{ post.language }}',
                                              '{{ g.locale }}');">{{ _('translate') }}
                </a>
                </span>
                {% endif %}
            </td>
        </tr>
    </table>

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - Microblog{% else %}Welcome to Microblog{% endif %}
{% endblock %}

{# {% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
{% endblock %} #}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    <li><a href="{{ url_for('main.explore') }}">Explore</a></li>
                </ul>                
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    {% else %}
                    <li><a href="{{ url_for('user.user', username=current_user.username) }}">Profile</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    {% endif %}
                </ul>
                {% if g.search_form %}
                <form class="navbar-form navbar-left" method="get" action="{{ url_for('main.search') }}".>
                    <div class="form-group">
                        {{ g.search_form.q(size=20, class='form-control', placeholder=g.search_form.q.label.text) }}
                    </div>
                </form>
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang(g.locale) }}
    <script>
        function translate(sourceElem, destElem, sourceLang, destLang) {
            $(destElem).html('<img src="{{ url_for('static', filename='loading.gif') }}">');
            $.post('/translate', {
                text: $(sourceElem).text(),
                source_language: sourceLang,
                dest_language: destLang,
            }).done(function(response) {
                $(destElem).text(response['text'])
            }).fail(function() {
                $(destElem).text("{{ _('Error: Could not contact server.') }}");
            });
        }
    </script>
{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Edit Profile</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Hi, %(username)s!', username=current_user.username) }}</h1>
    {% if form %}
    {{ wtf.quick_form(form) }}
    <br>
    {% endif %}
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ _('Newer posts') }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ _('Older posts') }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Sign In</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    <br>
    <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
    <p>
        Forgot Your Password?
        <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
    </p>
{% endblock %}

app/templates/search.html
{% extends "base.html" %}

{% block app_content %}
    <h1>{{ _('Search Results') }}</h1>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span>
                    {{ _('Previous results') }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ _('Next results') }}
                    <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>

{% endblock  %}

app/templates/user.html
{% extends "base.html" %}

{% block app_content %}
    <table class="table table-hover">
        <tr>
            <td width="256px"><img src="{{ user.avatar(256) }}"></td>
            <td>
                <h1>{{ _('User') }}: {{ user.username }}</h1>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}
                <p>{{ _('Was online') }}: {{ moment(user.last_seen).format('LLL') }}</p>
                {% endif %}
                <p>{{ _('%(count)d followers', count=user.followers.count()) }}, {{ _('%(count)d following', count=user.followed.count()) }}</p>
                <p>gender: {{ user.gender }}</p>
                {% if user == current_user %}
                <p><a href="{{ url_for('user.edit_profile') }}">{{ _('Edit your profile') }}</a></p>
                {% elif not current_user.is_following(user) %}
                <p>
                    <form action="{{ url_for('user.follow', username=user.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value=_('Follow'), class_='btn btn-default') }}
                    </form>
                </p>
                {% else %}
                <p>
                    <form action="{{ url_for('user.unfollow', username=user.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value=_('Unfollow'), class_='btn btn-default') }}
                    </form>
                </p>
                {% endif %}
            </td>
        </tr>
    </table>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ _('Newer posts') }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ _('Older posts') }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}